 
---
# tasks: Install Just-font
#
# Author: Luc Rutten
# File: tasks/main.yml
#
# Description:
#   Deploy fonts.

- name: "For OS: Windows, Arch: amd64"
  import_tasks: windows-amd64.yml
  when:
    - ansible_os_family == "Windows"
    - ansible_architecture == "64-bit"
