---
# tasks: sys-custom-fonts
#
# Author: Luc Rutten
# File: tasks/main.yml
#
# Description:
#   Deploy fonts.

- name: "Download fonts to local {{ ansible_env.SystemRoot }}/Fonts/{{ item.name }}"
  win_get_url:
    url: "{{ item.url }}"
    dest: "{{ ansible_env.SystemRoot }}/Fonts/{{ item.file }}"
  register: new_fonts
  with_items: "{{ fonts_repository }}"

- name: "Register Font in Windows registry"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts
    name: "{{ item.name }}"
    data: "{{ item.file }}"
    type: string
  with_items: "{{ fonts_repository }}"
