---
# tasks: sys-custom-fonts
#
# Author: Luc Rutten
# File: tasks/main.yml
#
# Description:
#   Deploy fonts.

- name: "Create local Ansible repository"
  win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ ansible_env.ProgramFiles }}/ansible/custom/fonts/"

- name: "Download fonts to local repository"
  win_get_url:
    url: "{{ item.url }}"
    dest: "{{ ansible_env.ProgramFiles }}/ansible/custom/fonts/{{ item.name }}"
  register: new_fonts
  with_items: "{{ fonts_repository }}"

- name: "Display new fonts"
  debug:
    msg: "{{ item.url }}"
#  when: "{{ item.changed == true }}"
  changed_when: False
  with_items: "{{ new_fonts.results }}"
  
- name: "Download template to local repository"
  win_template:
    src: install_fonts.vbs.j2
    dest: '{{ ansible_env.ProgramFiles }}/ansible/custom/fonts/install_fonts.vbs'
    force: no
